# Generated by Django 5.2.15 on 2026-07-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0002_seed_pledge_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgeplanitem',
            name='exclusive',
            field=models.BooleanField(default=False, help_text="Only available through this campaign — won't be sold at retail or late pledge."),
        ),
    ]
