# Generated by Django 5.2.15 on 2026-07-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0003_pledgeplanitem_exclusive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('bgg_designer_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='designers',
            field=models.ManyToManyField(blank=True, related_name='games', to='gamekeeper.designer'),
        ),
    ]
